### ISSUE TITLE
SimFin+ subsctiption, but data for free subscription

### ISSUE THREAD

**Issue by MislavSag** [matthiasgomolka/simfinapi#13]
Hi,

I have paid for SimFin+ subscription today, but the output from the functions is the same as before. That is, I don't get data from + subscription. For example, this call:
```
prices <- sfa_get_prices('F', api_key = 'myapikey', ratios = TRUE)
```
doesn't return the ratios and this call:
```
fs <- sfa_get_statement('F', statement = 'pl', start = as.Date('2015-01-01'), api_key = 'myapikey')
```
returns only one row of data.

**EDIT**
I have tried to get data directly, using web apis and it is working as expected:
```
url_prices <- paste0('https://simfin.com/api/v2/companies/prices?api-key=', api_key)
res <- httr::GET(url_prices, query = list(ticker = 'GE', ratios = TRUE))
txt <- httr::content(res, as = 'text')
json_output <- jsonlite::fromJSON(txt)
results <- as.data.frame(json_output$data)
colnames(results) <- unlist(json_output$columns)
head(results)
```
not sure why I don't get the same results using your functions?

**Comment by matthiasgomolka** [comment]
Hi thanks for getting in touch. The premium features are not yet fully implemented.

Regarding your first issue: This already works with the dev version which you can install using `remotes::install_github("https://github.com/matthiasgomolka/simfinapi")`.

The second one is not yet implemented. I will keep this issue open until it is.

**Comment by matthiasgomolka** [comment]
Fixed in branch [simfin_plus](https://github.com/matthiasgomolka/simfinapi/tree/simfin_plus).

To install the respective dev version use `remotes::install_github("https://github.com/matthiasgomolka/simfinapi/tree/simfin_plus")`

**Comment by matthiasgomolka** [comment]
Now also in the master branch: `remotes::install_github("https://github.com/matthiasgomolka/simfinapi")`

**Comment by MislavSag** [comment]
I confirm ratios are now included with SimFin subscription and all dates for statements are included.

Thanks for fast fix.

I have another issue now, but I am not sure if it is connected with subscription. When I set `statement` argument to `'all'`, it doesn't retrieve all statements but only the P&L.

**Comment by matthiasgomolka** [comment]
Did you have a look at the number of columns? The different statements are appended column-wise:

``` r
library(simfinapi)
options(sfa_api_key = Sys.getenv("SIMFIN_API_KEY"))
options(sfa_cache_dir = tempdir())

bs <- sfa_get_statement('F', statement = 'bs')
pl <- sfa_get_statement('F', statement = 'pl')
cf <- sfa_get_statement('F', statement = 'cf')
all <- sfa_get_statement('F', statement = 'all')

sapply(list(bs = bs, pl = pl, cf = cf, all = all), ncol)
#>  bs  pl  cf all 
#>  96  69  63 225
```

<sup>Created on 2020-12-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by MislavSag** [comment]
It works with 'all'. Maybe I did something wrong.
