### ISSUE TITLE
Error in colnamesIn

### ISSUE THREAD

**Issue by MislavSag** [matthiasgomolka/simfinapi#17]
I was using today your package after some time. I tried to retrieve prices for all sim fin ids:
```
ids <- sfa_get_entities(api_key = "xxx")
prices <- sfa_get_prices(SimFinId = ids$SimFinId, ratios = TRUE, api_key = "xxx")
```
I got an error:
```
  |=============================================================================================================                     |  84%Error in colnamesInt(x, neworder, check_dups = FALSE) : 
  argument specifying columns specify non existing column(s): cols[4]='Currency'
There were 50 or more warnings (use warnings() to see the first 50)   
```

---
EDIT by @matthiasgomolka: API key replaced by `xxx`.

**Comment by matthiasgomolka** [comment]
Confirmed. Thanks for the report. I'll look into this.

**Comment by matthiasgomolka** [comment]
The recent dev version (d0644712ac717457372f39612d60eaffdd6b4f3b) solves the problem. A single API request  did not return a currency. This is now filles with `NA`.

Please report, if you still have the issue.
