### ISSUE TITLE
ratios = TRUE not working for sfa_get_prices

### ISSUE THREAD

**Issue by thf24** [matthiasgomolka/simfinapi#19]
When trying to get the share price ratios along with the prices (via ratios = TRUE in sfa_get_prices), no ratios are being returned.

```r
stockratios <- sfa_get_prices("GOOG", 18, ratios = TRUE,
               api_key = "MY_API_KEY",
               cache_dir = tempdir())
```

columns returned for this call are only (ratios are missing):
SimFinId Ticker, Date, Currency, Open, High, Low, Close Adj., Close, Volume, Dividend, Common Shares Outstanding

**Comment by matthiasgomolka** [comment]
This is already fixed, but not yet pushed to CRAN. Please try `remotes::install_github("https://github.com/matthiasgomolka/simfinapi")` to install the current dev version. 

Then, your code returns the ratios as well.

**Comment by thf24** [comment]
great, thanks

**Comment by matthiasgomolka** [comment]
Just a sidenote: It's sufficient to provide either the ticker or the SimFin ID. You don't need both.
