### ISSUE TITLE
Error with sfa_get_statement() and a suggestion.

### ISSUE THREAD

**Issue by GitHubGeniusOverlord** [matthiasgomolka/simfinapi#24]
Hi.
Using the 
sfa_get_statement() Function I have a problem and a suggestion.

```r
tickers <- c('AAPL') #Tried also with GOOG and AMZN
sfa_get_statement(tickers, statement = "bs")
Error in data.table::setnames(DT, x[["columns"]]) : 
  Can't assign 95 names to a 190 column data.table
```
This error occurs whenever the statement variable is not "pl".

Which leads me to my suggestion. In the documentation https://www.rdocumentation.org/packages/simfinapi/versions/0.1.0/topics/sfa_get_statement
it is said that getting "all" statements together is reserved to SimFin+ User. Maybe it would be practical to have the sfa_get_statement() do that for you in case you are not a SimFin+ User and just internally join the results of the distinct calls. The same argument applies to the period statement. 

Vielen Dank! Thanks!

**Comment by matthiasgomolka** [comment]
Hi, thanks for raising the issue. 

Does this also occur when you use the latest version from Github? (i.e., can you provide a reprex including a session info?)

**Comment by matthiasgomolka** [comment]
Also thanks for the suggestion. Certainly a simplification for non SimFin+ users.

I think, it would be necessary to investigate if there is an easy way to check if an API key belongs to a free or paid account. Otherwise, it might get a bit messy if we would have to check if errors occur and then call the internal function to download the data three times.

**Comment by GitHubGeniusOverlord** [comment]
#Created with reprex()
#After updating the package from Github it seems the error changed, but there is still an error.

tickers <- c('AAPL') 
sfa_get_statement(tickers, statement = "bs")
#> Error in sfa_get_statement(tickers, statement = "bs"): konnte Funktion "sfa_get_statement" nicht finden

**Comment by matthiasgomolka** [comment]
Hi, this is the typical error when you did not load a package using `library()`. Try

r```

remotes::install_github("https://github.com/matthiasgomolka/simfinapi")
library(simfinapi)

sfa_set_api_key("YourApiKey")

tickers <- c('AAPL')
sfa_get_statement(tickers, statement = "bs")
```

This works fine for me.

**Comment by GitHubGeniusOverlord** [comment]
Hi, for me this fails at
```
> remotes::install_github("https://github.com/matthiasgomolka/simfinapi")
Error: Failed to install 'unknown package' from GitHub:
  cannot open destfile 'E:\TMP\RtmpovZV8U\file3b78723ff54', reason 'No such file or directory'
```

**Comment by GitHubGeniusOverlord** [comment]
Does not work for me. Now, after setting up a completely new R session, the outcome is this:
```
> sfa_get_statement(tickers, statement = "bs")
Warning messages:                                                                                                                      
1: 'cache_dir' not set. Defaulting to 'tempdir()'. Thus, API results will only be cached during this session. To learn why and how to cache results over the end of this session, see `?sfa_set_cache_dir`.

[This warning appears only once per session.] 
2: From 'SimFin' API: 'As non-SimFin+ user, please request exactly one financial year using the 'fyear' parameter.' 
> sfa_get_statement(tickers, statement = "bs")
Warning message:                                                                                                                       
From 'SimFin' API: 'As non-SimFin+ user, please request exactly one financial year using the 'fyear' parameter.' 
```
But, as you can see, no data is returned.

**Comment by matthiasgomolka** [comment]
> ```
> Warning message:                                                                                                                       
> From 'SimFin' API: 'As non-SimFin+ user, please request exactly one financial year using the 'fyear' parameter.' 
> ```

It seems as if you are not SimFin+ user. Thus, you need to specify `fyear`.

**Comment by GitHubGeniusOverlord** [comment]
It works now. Thanks! Problem solved ;)
