### ISSUE TITLE
Corrupted file in getting data from industries in "sfa_get_ref"

### ISSUE THREAD

**Issue by vsoler** [matthiasgomolka/simfinapi#37]
The sfa_get_ref() for "markets" woks well, but for "industries" it does not.

I get the following error message:

> > ref_data <- sfa_get_ref(ref_data = "industries")
> Error in data.table::fread(temp_csv, sep = ";", encoding = "UTF-8") : 
>   File 'C:\Users\USUARIO\AppData\Local\Temp\RtmpOc1a6z/industries.csv' does not exist or is non-readable. getwd()=='C:/Users/USUARIO/Documents/R/datacampScrape'
> Además: Warning message:
> In utils::unzip(temp_zip, exdir = tempdir()) : el archivo zip está corrupto

```{r}
sfa_set_api_key(api_key = "myAPIkeyHere")
ref_data <- sfa_get_ref(ref_data = "industries")
```

**Comment by matthiasgomolka** [comment]
Hello and thanks for raising the issue. 
Unfortunately, I cannot reproduce your problem. Maybe try again to make sure it's not a temporary problem on SimFin's side?
Or if you don't have SimFin+, maybe your daily limit on API calls was reached?
