### ISSUE TITLE
Cannot use sfa_get_entities output as input for sfa_get_info

### ISSUE THREAD

**Issue by ogig33** [matthiasgomolka/simfinapi#39]
Good evening! I am trying to pull financial data of all entities available in the Simfin API. This seems not possible since the outputs of `sfa_get_entities` are not accepted as inputs for `sfa_get_info` or `sfa_get_statements`. 

```r
# sample code
library(simfinapi)
sfa_set_api_key(api_key = "removedmykey")
sfa_set_cache_dir(path = "/Users/Documents/Finanzanlagen/R")
sfa_set_sfplus()

entities <- sfa_get_entities()
company_list1 <- sfa_get_info(ticker = entities$ticker)
company_list2 <- sfa_get_info(simfin_id = entities$simfin_id)

```

The call using tickers as input generates the following error:

```
Error in check_ticker(ticker) : 
  Assertion on 'ticker' failed: Must comply to pattern '^[A-Za-z0-9_\.\-]+$'.
```

The call using simfin_ids as input generates the following error:

```
Error in .deserialize_json(json = json, query = query, empty_array = empty_array,  : 
  The JSON document has an improper structure: missing or superfluous commas, braces, missing keys, etc.
```

I hope I am not missing anything basic here...

My Specs:
macOS 12.3.1
R version 4.1.3
simfinapi package CRAN release and Github development release tried both with same behavior

**Comment by matthiasgomolka** [comment]
Hi and thanks for the report. It might be the case that naming rules have changed since I implemented the input checks. This has happened before. 

Unfortunately, I won't be able to look into this before next week.

**Comment by snvv** [comment]
Hello
If you try company_list1 <- sfa_get_info(ticker = entities$ticker[1:2200]) it works.
May be there is a limit in the number of tickers,

**Comment by matthiasgomolka** [comment]
Fixed.
