### ISSUE TITLE
sfa_get_entities does not return the company names

### ISSUE THREAD

**Issue by GitHubGeniusOverlord** [matthiasgomolka/simfinapi#40]
Hello,

the 
sfa_get_entities
function says in its documentation that "Get a table of all available 'SimFin' ID's with ticker and name."
Of this it only returns the first two, simfin_id and ticker, but not name. I guess this is just a little detail that is missing.

Thanks!

**Comment by matthiasgomolka** [comment]
Thanks for the report. The documentation ist fixed now.
