### ISSUE TITLE
New V3 api

### ISSUE THREAD

**Issue by msperlin** [matthiasgomolka/simfinapi#45]
Hi Matthias,

From my email, I received the news about simfin. It is a now a private company, fully funded. This might be good or bad news for the future (usually bad).

The new V3 api is already out, and this might require changes in simfinapi:

![image](https://user-images.githubusercontent.com/10583352/222730223-30fcfdc8-3c4a-43b6-819c-1740f83f2fd4.png)

**Comment by matthiasgomolka** [comment]
Hi Marcelo,

thanks for the heads up. I also got the e-mail and the SimFin Team already made a PR: https://github.com/matthiasgomolka/simfinapi/pull/42. I'll trigger a new CRAN release soon.

Also, I'm already in contact with SimFin regarding the update to the API V3.
