### ISSUE TITLE
API V3 now mandatory

### ISSUE THREAD

**Issue by thf24** [matthiasgomolka/simfinapi#51]
Hi,

we shut-down the legacy API now, so connection errors are to be expected on the current "main" branch. 

What is the state of the V3 API branch, is there any way we can assist to make the merge to main happen? 

https://github.com/matthiasgomolka/simfinapi/tree/api_v3

Kind regards

Thomas from SimFiin

**Comment by matthiasgomolka** [comment]
Many functions already work with the new API but the unit tests require a fair bit of work since many things changed.

**Comment by matthiasgomolka** [comment]
I just submitted a new release to CRAN. If everything goes smothely it should be available on CRAN within the next few days.

**Comment by matthiasgomolka** [comment]
Version 1.0.0 was published on 2024-02-28, so closing this now.
