### ISSUE TITLE
Return data.tables with consistent lowercase "strict" variable names

### ISSUE THREAD

**Issue by matthiasgomolka** [matthiasgomolka/simfinapi#8]
It is suboptimal that variable names in returned `data.table`s are not fully lowercase and (worse) contain spaces. This should be cleaned up consistently, maybe via a function `setcleannames()`?

**Comment by MislavSag** [comment]
Can I recommend using janitor::clean_names?

**Comment by matthiasgomolka** [comment]
Hi and thanks for the suggestion! I know `janitor`, but I'm reluctanct to import a package with a bunch of new dependencies in order to use a single function from it. Thus, I will likely borrow from `janitor`s ideas, but will implement it using `base` functions (or maybe `stringi`). Since the column names from the API are predictible, it should not be necessary cover all the cases, which `janitor` covers.

**Comment by joshuaulrich** [comment]
> maybe `stringi`

That package has a very long compile time, in case that may affect your decision to use it.

**Comment by matthiasgomolka** [comment]
> > maybe `stringi`
> 
> That package has a very long compile time, in case that may affect your decision to use it.

Thanks for the reminder.

**Comment by matthiasgomolka** [comment]
Solved in 492dc358d52d165642d30d23779dff73aa8aacbc.
